// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model_Builder_Journal_Example.Data;

#nullable disable

namespace Model_Builder_Journal_Example.Migrations
{
    [DbContext(typeof(Model_Builder_Journal_ExampleContext))]
    partial class Model_Builder_Journal_ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.Journal", b =>
                {
                    b.Property<string>("UserOwnerNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JournalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserOwnerNumber");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.User", b =>
                {
                    b.Property<string>("UserNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FristName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserNumber");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserNumber = "001",
                            FristName = "Adminstrator"
                        });
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.UserJournal", b =>
                {
                    b.Property<string>("UserEditorNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JournalNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserEditorNumber", "JournalNumber");

                    b.HasIndex("JournalNumber");

                    b.ToTable("UserJournals");
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.Journal", b =>
                {
                    b.HasOne("Model_Builder_Journal_Example.Models.User", "UserOwner")
                        .WithMany("Journals")
                        .HasForeignKey("UserOwnerNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOwner");
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.UserJournal", b =>
                {
                    b.HasOne("Model_Builder_Journal_Example.Models.Journal", "Journal")
                        .WithMany("UserJournals")
                        .HasForeignKey("JournalNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model_Builder_Journal_Example.Models.User", "UserEditor")
                        .WithMany("UserJournals")
                        .HasForeignKey("UserEditorNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("UserEditor");
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.Journal", b =>
                {
                    b.Navigation("UserJournals");
                });

            modelBuilder.Entity("Model_Builder_Journal_Example.Models.User", b =>
                {
                    b.Navigation("Journals");

                    b.Navigation("UserJournals");
                });
#pragma warning restore 612, 618
        }
    }
}
